name: Build and Deploy API in PROD

on:
  push:
    branches:
      - main
jobs:
  # Print variables for logging and debugging purposes
  checkEnv:
    name: Check Env variables
    runs-on: ubuntu-latest
    steps:
    - name: Print Env Vars
      run: |
        echo Git Base Ref: ${{ github.base_ref }}
        echo Git Build ID: ${{ github.event.number }}
        echo Git Pull Request Ref: ${{ github.event.pull_request.head.sha }}
        echo Git Ref Name: ${{ github.ref_name }}
        echo OC CLI Version: $(oc version)
